package main

import (
    _ "IOTino/docs" // docs is generated by Swag CLI, you have to import it.
    "IOTino/pkg/MQTT"
    "IOTino/pkg/settings"
    "IOTino/routers"
    "fmt"
)

// @title IOTino
// @version 0.0.1
// @description The worst IOT website in Laohe Mountain Institute of Technology
// @host localhost:8080
func main() {

    var err error

    settings.InitSettings()

    println("set up MQTT broker")
    go MQTT.MQTT()

    println("setup web app server")
    r := routers.InitRouter()

    if err = r.Run(settings.HttpPort); err != nil {
        fmt.Println(err)
        return
    }
}
