package main

import (
	"IOTino/Config"
	"IOTino/Controller"
	"IOTino/Models"
	_ "IOTino/docs" // docs is generated by Swag CLI, you have to import it.
	"fmt"
	"github.com/gin-gonic/gin"
	"github.com/swaggo/files"
	"github.com/swaggo/gin-swagger"
	"gorm.io/driver/mysql"
	"gorm.io/gorm"
)

// @title IOTino
// @version 0.0.1
// @description The worst IOT website in Laohe Mountain Institute of Technology
// @host localhost:8080
func main() {

	var err error

	println(">>> Stage 1: connect to database")

	if Config.DB, err = gorm.Open(mysql.Open(Config.DSN), &gorm.Config{}); err != nil {
		fmt.Println(err)
		return
	}

	if err := Config.DB.AutoMigrate(&Models.User{}, &Models.Device{}, &Models.Location{}); err != nil {
		fmt.Println(err)
		return
	}

	println(">>> Stage 2: setup mqtt broker")
	go Controller.MQTT()

	println(">>> Stage 3: setup web app server")
	r := gin.Default()
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	group := r.Group("/api")
	{
		group.POST("/register", Models.CreateUser)
	}

	if err := r.Run(); err != nil {
		fmt.Println(err)
		return
	}
}
